results_dir: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit_retrain'
key: 'nvidia_tlt'
data:
  train_dataset_path: "/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/data/split_16bit/train"
  val_dataset_path: "/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/data/split_16bit/val"
  preprocess_mode: 'torch'
  image_mean: [0.449]
augment:
  enable_color_augmentation: True
  enable_center_crop: True
train:
  qat: False
  pretrained_model_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit/efficientnet-b0_pruned/model_pruned.tlt'
  batch_size_per_gpu: 64
  num_epochs: 8
  optim_config:
    optimizer: 'sgd'
  lr_config:
    scheduler: 'cosine'
    learning_rate: 0.05
    soft_start: 0.05
  reg_config:
    type: 'L2'
    scope: ['conv2d', 'dense']
    weight_decay: 0.00005
model:
  arch: 'efficientnet-b0'
  input_image_size: [1,256,256]
  input_image_depth: 16
evaluate:
  dataset_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/data/split_16bit/test'
  model_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit_retrain/weights/efficientnet-b0_008.tlt'
  top_k: 3
  batch_size: 256
  n_workers: 8
inference:
  model_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit_retrain/weights/efficientnet-b0_008.tlt'
  image_dir: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/data/split_16bit/test/aeroplane'
  classmap: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit_retrain/classmap.json'
export:
  model_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/output_16bit_retrain/weights/efficientnet-b0_008.tlt'
  output_path: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/export/efficientnet-b0.etlt'
  data_type: 'fp32'
  engine_file: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/export/efficientnet-b0.fp32.engine'
  cal_image_dir: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/data/split_16bit/test'
  cal_data_file: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/export/calib.tensorfile'
  cal_cache_file: '/home/jupyter/notebooks/tao_launcher_starter_kit/classification_tf2/classification_16bit/export/cal.bin'
  batch_size: 16
  max_batch_size: 16
  batches: 10