results_dir: 'RESULTSDIR'
key: 'ENC_KEY'
data:
  train_dataset_path: "/workspace/tao-experiments/data/split/train"
  val_dataset_path: "/workspace/tao-experiments/data/split/val"
  preprocess_mode: 'torch'
augment:
  enable_color_augmentation: True
  enable_center_crop: True
train:
  qat: True
  pretrained_model_path: 'PRUNEDMODEL'
  batch_size_per_gpu: 64
  num_epochs: 80
  optim_config:
    optimizer: 'sgd'
  lr_config:
    scheduler: 'cosine'
    learning_rate: 0.05
    soft_start: 0.05
  reg_config:
    type: 'L2'
    scope: ['conv2d', 'dense']
    weight_decay: 0.00005
model:
  arch: 'efficientnet-b0'
  input_image_size: [3,256,256]
  input_image_depth: 8
evaluate:
  dataset_path: '/workspace/tao-experiments/data/split/test'
  model_path: 'EVALMODEL'
  top_k: 3
  batch_size: 256
  n_workers: 8
inference:
  model_path: 'EVALMODEL'
  image_dir: '/workspace/tao-experiments/data/split/test/aeroplane'
  classmap: 'RESULTSDIR/classmap.json'
export:
  model_path: 'EVALMODEL'
  output_path: 'EXPORTDIR/efficientnet-b0.qat.etlt'
  data_type: 'int8'
  engine_file: 'EXPORTDIR/efficientnet-b0.qat.engine'
  batch_size: 16
  max_batch_size: 16